services:
  db:
    image: postgres:14.8
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hasker
      - POSTGRES_USER=hasker
      - POSTGRES_PASSWORD=hasker_test_site_1

  web:
    build: .
    command: ["bash", "-c", "chmod 777 /hasker/wait-for-it.sh && /hasker/wait-for-it.sh db:5432 -- uwsgi --ini /hasker/config/uwsgi/uwsgi.ini"]
#    ["/hasker/wait-for-it.sh", "db:5432", "--", "uwsgi", "--ini", "hasker/config/uwsgi/uwsgi.ini"]
#              "python", "/hasker/manage.py", "runserver", "--settings=hasker.settings.prod", "0.0.0.0:8000"]
    restart: always
    volumes:
      - .:/hasker
    ports:
      - '8000:8000'
    environment:
      - DJANGO_SETTINGS_MODULE=hasker.settings.prod
      - POSTGRES_DB=hasker
      - POSTGRES_USER=hasker
      - POSTGRES_PASSWORD=hasker_test_site_1
    depends_on:
      - db

  nginx:
    image: nginx:1.23.1
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/hasker
    ports:
      - "80:80"