services:
  db:
    image: postgres:14.8
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hasker
      - POSTGRES_USER=hasker
      - POSTGRES_PASSWORD=hasker_test_site_1

  web:
    build: .
    command: ["bash", "-c", "chmod 777 /hasker/hasker_start.sh && /hasker/hasker_start.sh"]
    restart: always
    volumes:
      - .:/hasker
    ports:
      - '8000:8000'
    environment:
      - DJANGO_SETTINGS_MODULE=hasker.settings.prod
      - POSTGRES_DB=hasker
      - POSTGRES_USER=hasker
      - POSTGRES_PASSWORD=hasker_test_site_1
    depends_on:
      - db

  nginx:
    image: nginx:1.23.1
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/hasker
    ports:
      - "80:80"