# Generated by Django 4.2.3 on 2023-07-15 09:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=250)),
                ('body', models.TextField()),
                ('publish', models.DateField(default=datetime.datetime(2023, 7, 15, 9, 52, 56, 956749, tzinfo=datetime.timezone.utc))),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_question', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish'],
            },
        ),
        migrations.CreateModel(
            name='PostAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=250)),
                ('body', models.TextField()),
                ('publish', models.DateField(default=datetime.datetime(2023, 7, 15, 9, 52, 56, 957244, tzinfo=datetime.timezone.utc))),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_answer', to=settings.AUTH_USER_MODEL)),
                ('question_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_answer', to='hasker_app.postquestion')),
            ],
            options={
                'ordering': ['-publish'],
            },
        ),
        migrations.AddIndex(
            model_name='postquestion',
            index=models.Index(fields=['-publish'], name='hasker_app__publish_575834_idx'),
        ),
        migrations.AddIndex(
            model_name='postanswer',
            index=models.Index(fields=['-publish'], name='hasker_app__publish_0c2ef2_idx'),
        ),
    ]
