# Generated by Django 4.2.3 on 2023-07-15 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasker_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postanswer',
            name='for_slug',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='postanswer',
            name='publish',
            field=models.DateField(default=datetime.datetime(2023, 7, 15, 11, 56, 37, 686602, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postquestion',
            name='publish',
            field=models.DateField(default=datetime.datetime(2023, 7, 15, 11, 56, 37, 685956, tzinfo=datetime.timezone.utc)),
        ),
    ]
