# Generated by Django 4.2.3 on 2023-07-15 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasker_app', '0003_remove_postanswer_for_slug_remove_postanswer_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postanswer',
            name='publish',
            field=models.DateField(default=datetime.datetime(2023, 7, 15, 12, 14, 12, 190887, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postquestion',
            name='publish',
            field=models.DateField(default=datetime.datetime(2023, 7, 15, 12, 14, 12, 190325, tzinfo=datetime.timezone.utc)),
        ),
    ]
