# Generated by Django 4.2.3 on 2023-07-17 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasker_app', '0005_alter_postanswer_publish_alter_postquestion_publish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postanswer',
            name='publish',
            field=models.DateField(default=datetime.datetime(2023, 7, 17, 18, 57, 19, 100984, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postquestion',
            name='publish',
            field=models.DateField(default=datetime.datetime(2023, 7, 17, 18, 57, 19, 100414, tzinfo=datetime.timezone.utc)),
        ),
    ]
