# Generated by Django 4.2.3 on 2023-07-20 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasker_app', '0007_alter_postanswer_publish_alter_postquestion_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postanswer',
            name='publish',
            field=models.DateField(default=datetime.datetime(2023, 7, 20, 11, 41, 8, 563584, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postquestion',
            name='publish',
            field=models.DateField(default=datetime.datetime(2023, 7, 20, 11, 41, 8, 563086, tzinfo=datetime.timezone.utc)),
        ),
    ]
