# Generated by Django 4.2.3 on 2023-07-20 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasker_app', '0008_alter_postanswer_publish_alter_postquestion_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='postquestion',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postanswer',
            name='publish',
            field=models.DateField(default=datetime.datetime(2023, 7, 20, 15, 0, 30, 200128, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postquestion',
            name='publish',
            field=models.DateField(default=datetime.datetime(2023, 7, 20, 15, 0, 30, 199611, tzinfo=datetime.timezone.utc)),
        ),
    ]
