# Generated by Django 4.2.3 on 2023-07-22 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasker_app', '0011_alter_postanswer_options_alter_postquestion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
        migrations.AlterField(
            model_name='postanswer',
            name='publish',
            field=models.DateField(default=datetime.datetime(2023, 7, 22, 10, 10, 47, 331442, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postquestion',
            name='publish',
            field=models.DateField(default=datetime.datetime(2023, 7, 22, 10, 10, 47, 330533, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='postquestion',
            name='tags',
            field=models.ManyToManyField(related_name='question', to='hasker_app.tag'),
        ),
    ]
