# Generated by Django 4.2.3 on 2023-07-24 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasker_app', '0013_alter_postanswer_publish_alter_postquestion_publish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postquestion',
            options={'ordering': ['-rating', '-publish']},
        ),
        migrations.AlterField(
            model_name='postanswer',
            name='publish',
            field=models.DateField(default=datetime.datetime(2023, 7, 24, 19, 40, 2, 601671, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postquestion',
            name='publish',
            field=models.DateField(default=datetime.datetime(2023, 7, 24, 19, 40, 2, 600831, tzinfo=datetime.timezone.utc)),
        ),
    ]
