# Generated by Django 4.2.3 on 2023-07-26 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasker_app', '0015_postquestion_views_alter_postanswer_publish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postanswer',
            name='publish',
            field=models.DateField(default=datetime.datetime(2023, 7, 26, 18, 48, 25, 659237, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postquestion',
            name='publish',
            field=models.DateField(default=datetime.datetime(2023, 7, 26, 18, 48, 25, 658295, tzinfo=datetime.timezone.utc)),
        ),
    ]
