# Generated by Django 4.2.3 on 2023-07-28 20:02

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hasker_app', '0016_alter_postanswer_publish_alter_postquestion_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='postanswer',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='answers_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postquestion',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='questions_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postanswer',
            name='publish',
            field=models.DateField(default=datetime.datetime(2023, 7, 28, 20, 2, 28, 771174, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postquestion',
            name='publish',
            field=models.DateField(default=datetime.datetime(2023, 7, 28, 20, 2, 28, 770143, tzinfo=datetime.timezone.utc)),
        ),
    ]
