# Generated by Django 4.2.3 on 2023-07-31 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasker_app', '0019_alter_postanswer_options_alter_postanswer_publish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postanswer',
            name='answer_is_correct',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='postanswer',
            name='publish',
            field=models.DateField(default=datetime.datetime(2023, 7, 31, 19, 53, 58, 112913, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postquestion',
            name='publish',
            field=models.DateField(default=datetime.datetime(2023, 7, 31, 19, 53, 58, 111405, tzinfo=datetime.timezone.utc)),
        ),
    ]
