# Generated by Django 4.2.3 on 2023-08-04 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasker_app', '0020_postanswer_answer_is_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postanswer',
            name='publish',
            field=models.DateField(default=datetime.datetime(2023, 8, 4, 19, 1, 21, 347089, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postquestion',
            name='publish',
            field=models.DateField(default=datetime.datetime(2023, 8, 4, 19, 1, 21, 345653, tzinfo=datetime.timezone.utc)),
        ),
    ]
